version: 1
policy:
  pullRequests: public
tasks:
  $if: taskcluster_root_url == "https://taskcluster.internal.wpgapi.uk"
  then:
    $let:
      imageName: gcr.io/wpg-internal/taskcluster-operator
      defaults:
        created: { $fromNow: '' }
        deadline: { $fromNow: '3 hours' }
        expires: { $fromNow: '10 days' }
        provisionerId: shared
        workerType: multistage-docker
        scopes:
          - secrets:get:shared/github
          - secrets:get:shared/cloudbuild-service-account
        metadata:
          name: Build taskcluster-operator
          description: Build & push taskcluster-operator
          owner: '${event.sender.login}@users.noreply.github.com'
          source: '${event.repository.url}'
    in:
      - $if: (tasks_for == "github-push") && (event.ref == "refs/heads/main")
        then:
          $mergeDeep:
            - { $eval: defaults }
            - routes:
                - notify.slack-channel.C9Z43K24F.on-any
              extra:
                docker:
                  imagesPushed:
                    - ${imageName}:${event.after}
              payload:
                steps:
                  $flatten:
                    - image: gcr.io/wpg-internal/ci-bootstrap
                    - image: bitnami/git
                      command: ["/bin/bash", "-c"]
                      args:
                        - git clone ${event.repository.html_url} . && git checkout ${event.after}
                    - image: docker
                      args: [ "build", ".", "-t", "${imageName}:${event.after}" ]
                    - image: docker
                      args: [ "push", "${imageName}:${event.after}" ]
      - $if: (tasks_for == "github-pull-request") && event["action"] in ["opened", "reopened", "synchronize"]
        then:
          $mergeDeep:
            - { $eval: defaults }
            - payload:
                steps:
                  - image: gcr.io/wpg-internal/ci-bootstrap
                  - image: bitnami/git
                    command: ["/bin/bash", "-c"]
                    args:
                      - >-
                        git clone ${event.repository.html_url} .
                        && git checkout ${event.pull_request.head.sha}
                        && git rebase ${event.pull_request.base.sha}
                  - image: docker
                    args: [ "build", ".", "--secret" ]
              metadata:
                name: PR test taskcluster-operator
                description: Test taskcluster-operator for a PR
