apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskcluster-purge-cache
  labels:
    app.kubernetes.io/name: taskcluster-purge-cache
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-purge-cache-secrets
    app.kubernetes.io/part-of: taskcluster
