apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: taskcluster-queue-expiretaskgroupsizes
  labels: &ref_0
    app.kubernetes.io/name: taskcluster-queue
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-queue-expiretaskgroupsizes
    app.kubernetes.io/part-of: taskcluster
spec:
  schedule: 0 0 * * *
  jobTemplate:
    metadata:
      labels: *ref_0
    spec:
      template:
        metadata:
          labels: *ref_0
        spec:
          restartPolicy: OnFailure
          activeDeadlineSeconds: 86400
          containers:
            - name: taskcluster-queue-expiretaskgroupsizes
              image: '{{ .Values.dockerImage }}'
              imagePullPolicy: Always
              args:
                - queue/expireTaskGroupSizes
              resources:
                requests:
                  cpu: '{{ .Values.queue.procs.expireTaskGroupSizes.cpu }}'
                  memory: '{{ .Values.queue.procs.expireTaskGroupSizes.memory }}'
              env:
                - name: TASKCLUSTER_ROOT_URL
                  value: '{{ .Values.rootUrl }}'
                - name: USE_KUBERNETES_DNS_SERVICE_DISCOVERY
                  value: '{{ .Values.useKubernetesDnsServiceDiscovery }}'
                - name: NODE_ENV
                  value: production
              envFrom:
                - secretRef:
                    name: taskcluster-queue
