apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskcluster-notify
  labels:
    app.kubernetes.io/name: taskcluster-notify
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-notify-secrets
    app.kubernetes.io/part-of: taskcluster
