apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskcluster-secrets
  labels:
    app.kubernetes.io/name: taskcluster-secrets
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-secrets-secrets
    app.kubernetes.io/part-of: taskcluster
