apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskcluster-github
  labels:
    app.kubernetes.io/name: taskcluster-github
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-github-secrets
    app.kubernetes.io/part-of: taskcluster
