apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskcluster-hooks
  labels:
    app.kubernetes.io/name: taskcluster-hooks
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-hooks-secrets
    app.kubernetes.io/part-of: taskcluster
