kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: taskcluster-secrets-secrets-read
  labels:
    app.kubernetes.io/name: taskcluster-secrets
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-secrets-secrets
    app.kubernetes.io/part-of: taskcluster
subjects:
  - kind: User
    name: taskcluster-secrets
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: taskcluster-secrets-secrets-read
  apiGroup: rbac.authorization.k8s.io
