kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: taskcluster-references-secrets-read
  labels:
    app.kubernetes.io/name: taskcluster-references
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-references-secrets
    app.kubernetes.io/part-of: taskcluster
rules:
  - apiGroups:
      - ''
    resources:
      - secrets/taskcluster-references
    verbs:
      - get
      - watch
      - list
