apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskcluster-worker-manager
  labels:
    app.kubernetes.io/name: taskcluster-worker-manager
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-worker-manager-secrets
    app.kubernetes.io/part-of: taskcluster
