apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskcluster-web-server
  labels:
    app.kubernetes.io/name: taskcluster-web-server
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-web-server-secrets
    app.kubernetes.io/part-of: taskcluster
