apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskcluster-auth
  labels:
    app.kubernetes.io/name: taskcluster-auth
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-auth-secrets
    app.kubernetes.io/part-of: taskcluster
