apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskcluster-index
  labels:
    app.kubernetes.io/name: taskcluster-index
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-index-secrets
    app.kubernetes.io/part-of: taskcluster
