apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskcluster-built-in-workers
  labels:
    app.kubernetes.io/name: taskcluster-built-in-workers
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-built-in-workers-secrets
    app.kubernetes.io/part-of: taskcluster
