apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskcluster-queue
  labels:
    app.kubernetes.io/name: taskcluster-queue
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-queue-secrets
    app.kubernetes.io/part-of: taskcluster
