kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: taskcluster-hooks-secrets-read
  labels:
    app.kubernetes.io/name: taskcluster-hooks
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-hooks-secrets
    app.kubernetes.io/part-of: taskcluster
rules:
  - apiGroups:
      - ''
    resources:
      - secrets/taskcluster-hooks
    verbs:
      - get
      - watch
      - list
