apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskcluster-object
  labels:
    app.kubernetes.io/name: taskcluster-object
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-object-secrets
    app.kubernetes.io/part-of: taskcluster
