apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskcluster-ui
  labels:
    app.kubernetes.io/name: taskcluster-ui
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-ui-secrets
    app.kubernetes.io/part-of: taskcluster
