apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskcluster-references
  labels:
    app.kubernetes.io/name: taskcluster-references
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-references-secrets
    app.kubernetes.io/part-of: taskcluster
